//import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Router from 'next/router';
import { ChakraProvider, extendTheme  } from '@chakra-ui/react'
import { SessionProvider } from "next-auth/react"
import chakraTheme from '@chakra-ui/theme'
import NextNProgress from 'nextjs-progressbar';
import Head from 'next/head';


const { Button } = chakraTheme.components
// const colors = {
//     brand: {
//       primary: "#25316D",
//       secondary: "#5F6F94",
//       light: "#ffffff",
//       dark: "#1F1F1F",
//       "light-grey": "#F9F9F9",
//       "light-blue": "#F6FBFF",
//       warning: "#FFC107",
//       "warning-soft": "#FFFAEB",
//       "warning-hover": "#ffac07",
//       success: "#20D15C",
//       error: "#EE5757",
//     },
//     type: {
//       primary: "#0B1E74",
//       heading: "#3D3D3D",
//       strong: "#161616",
//       strongest: "#181818",
//       soft: "#787878",
//       softest: "#A8A8A8",
//     },
//   };
const theme = extendTheme({
  //  colors,
  components: {
    Button,
  },
})


export default function App({ 
    Component, 
    pageProps: { session, ...pageProps }
}: AppProps) {
  return (
    <SessionProvider session={session}>
        <ChakraProvider theme={theme}>
            <NextNProgress />
            <Head>
                <title>Social Media Kita</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
        </ChakraProvider>
    </SessionProvider>
  )
}
