//import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Router from 'next/router';
import { ChakraProvider  } from '@chakra-ui/react'
import { SessionProvider } from "next-auth/react"

import NextNProgress from 'nextjs-progressbar';
import Head from 'next/head';
import theme from "@/lib/theme";




export default function App({ 
    Component, 
    pageProps: { session, ...pageProps }
}: AppProps) {
  return (
    <SessionProvider session={session}>
        <ChakraProvider theme={theme}>
            <NextNProgress />
            <Head>
                <title>Social Media Kita</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
        </ChakraProvider>
    </SessionProvider>
  )
}
